on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: |
          git config --local user.email "209262+backpaper0@users.noreply.github.com"
          git config --local user.name "Uragami Taichi(GitHub Actions)"
      - run: |
          set -eux
          git rm -fr docs/${{ github.event.number }}
          git commit -m "Pull request closed"
          git push origin gh-pages
