name: deploy

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: |
          git config --local user.email "209262+backpaper0@users.noreply.github.com"
          git config --local user.name "Uragami Taichi(GitHub Actions)"
      - run: touch .sub-path
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: echo /nightly > .sub-path
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
      - run: echo /${{ github.event.number }} > .sub-path
        if: ${{ github.event_name == 'pull_request' }}
      - run: echo /${{ github.ref_name }} > .sub-path
        if: ${{ github.event_name == 'workflow_dispatch' }}
      - run: BASE_URL_SUB_PATH=$(cat .sub-path) npm run build -- --out-dir build$(cat .sub-path)
      - run: ./scripts/commit_document.sh
      - run: git push origin gh-pages
