name: deploy

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: |
          git config --local user.email "209262+backpaper0@users.noreply.github.com"
          git config --local user.name "Uragami Taichi(GitHub Actions)"
      - run: touch .sub-path
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: echo /nightly > .sub-path
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
      - run: echo /${{ github.event.number }} > .sub-path
        if: ${{ github.event_name == 'pull_request' }}
      - run: echo /${{ github.ref_name }} > .sub-path
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
      - run: echo /${{ github.ref_name }} > .sub-path
        if: ${{ github.event_name == 'workflow_dispatch' }}
      - run: BASE_URL_SUB_PATH=$(cat .sub-path) npm run build -- --out-dir build$(cat .sub-path)
      - run: |
          set -eux
          
          git rm -fr docs
          git commit -m "Temporary"
          mv build docs
          git add docs
          git stash
          git fetch --no-tags --depth=1 origin gh-pages
          git checkout gh-pages
          buildPath=docs$(cat .sub-path)
          
          if [ ${buildPath} = docs ] ; then
            # 以下の格納ディレクトリを除くファイル・ディレクトリを削除する
            # nightly ... developブランチに対応
            # セマンティックバージョン ... タグに対応
            # 整数 ... プルリクエストに対応
            cd docs
            git rm -fr --ignore-unmatch $(ls | grep -vE '^(\d+|\d+\.\d+\.\d+|nightly)$')
            cd ..
          else
            git rm -fr --ignore-unmatch ${buildPath}
          fi
          
          ammend=""
          git status
          if [ -n "$(git status --short)" ]; then
            git commit -m "WIP"
          	ammend="--amend"
          fi
          
          git stash pop
          git status
          if [ -n "$(git status --short)" ]; then
            git commit ${ammend} -m "Update document"
            git push origin gh-pages
          fi
